"""added isaccepted and temp field

Revision ID: 143fced9d50f
Revises: 6e309469eb77
Create Date: 2025-12-02 00:04:22.061650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '143fced9d50f'
down_revision: Union[str, Sequence[str], None] = '6e309469eb77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('is_accepted', sa.Boolean(), nullable=False))
    op.add_column('employees', sa.Column('employee_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'employee_name')
    op.drop_column('employees', 'is_accepted')
    # ### end Alembic commands ###
