"""added register table

Revision ID: 6d113bc77b8c
Revises: 143fced9d50f
Create Date: 2025-12-03 00:11:16.557681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d113bc77b8c'
down_revision: Union[str, Sequence[str], None] = '143fced9d50f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('register',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('shop_type', sa.String(), nullable=False),
    sa.Column('mobile_number', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.add_column('accounts', sa.Column('mobile_number', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('employee_mobile_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'employee_mobile_number')
    op.drop_column('accounts', 'mobile_number')
    op.drop_table('register')
    # ### end Alembic commands ###
