"""added shopname field

Revision ID: a80cc72bbb6f
Revises: 6d113bc77b8c
Create Date: 2025-12-09 01:08:03.304479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a80cc72bbb6f'
down_revision: Union[str, Sequence[str], None] = '6d113bc77b8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('register', sa.Column('shop_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('register', 'shop_name')
    # ### end Alembic commands ###
